GET http://localhost:8080/patients?name=Jo

###

GET http://localhost:8080/patient/2

###

DELETE http://localhost:8080/patient/3

###

POST http://localhost:8080/patients
Content-Type: application/json

{
  "id": 0,
  "name": "Alexandre",
  "surname": "Humbert",
  "email": "bgdu88@gmail.com",
  "phone": "0123456789",
  "birth_date": "2003-04-23T16:35:00.000+00:00"
}

###

POST http://localhost:8080/patients
Content-Type: application/json

{
  "id": 1,
  "name": "Léo",
  "surname": "Gueffier",
  "email": "bgdu51@gmail.com",
  "phone": "9876543210",
  "birth_date": "2002-06-15T16:35:00.000+00:00"
}

###

POST http://localhost:8080/specialist
Content-Type: application/json

{
  "id": 0,
  "center_id": 0,
  "name": "Alexandre",
  "specialty": "Cardiologue",
  "email": "bgdu88@gmail.com",
  "phone": "6666666666",
  "birth_date": "2003-04-23T16:35:00.000+00:00",
  "password": "test",
  "is_admin": true
}