GET http://localhost:8080/patients?name=Jo

###

GET http://localhost:8080/patient/2

###

DELETE http://localhost:8080/patient/3

###

POST http://localhost:8080/patients
Content-Type: application/json

{
  "id": 0,
  "name": "Alexandre",
  "surname": "Humbert",
  "email": "bgdu88@gmail.com",
  "phone": "0123456789",
  "birth_date": "2003-04-23T16:35:00.000+00:00"
}

###

POST http://localhost:8080/patients
Content-Type: application/json

{
  "id": 2,
  "name": "John",
  "birthDate": "2019-10-07T00:00:01.084+00:00"
}