GET http://localhost:8080/patients

###

GET http://localhost:8080/specialists

###

DELETE http://localhost:8080/patient/3

###

POST http://localhost:8080/patients
Content-Type: application/json

{
  "name": "Alexandre",
  "surname": "Humbert",
  "email": "bgdu88@gmail.com",
  "phone": "0123456789",
  "birthdate": "2003-04-23T16:35:00.000+00:00"
}

###

POST http://localhost:8080/specialists
Content-Type: application/json

{
  "centerid": 1,
  "name": "Alexandre",
  "specialty": "Cardiologue",
  "email": "bgdu88@gmail.com",
  "phone": "6666666666",
  "isadmin": true
}